const form = [
  "form-material",
  "form-field",
  "form-check",
  "form-inline",
  "form-file",
  "form-material-bordered",
  "form-control",
  "form-group",
  "form-group-item",
  "form-custom-select",
  "form-switch",
  "form-default",
  "form-slider",
  "form-slider-thin",
  "form-slider-small",
  "form-slider-large",
  "form-helper-valid",
  "form-helper-invalid",
];
export default form
